import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSWR from "swr";
import Article from "@/components/article";

export default function Home() {
  const { data } = useSWR("/api/data", (url) =>
    fetch(url).then((res) => res.json())
  );

  return (
    <>
      <Head>
        <title>はてブ毎時ランキング</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <ol>
          {data &&
            Object.entries(data).map(([key, value]) => {
              return (
                <li className='entry' key={key}>
                  <Article hatebData={value}></Article>
                </li>
              );
            })}
        </ol>
      </main>
    </>
  );
}
